meta_product_name: "Parkingshare"
meta_title: "Parkingshare - Find the parking that you need"
meta_description: "Find the parking that you need, earn the money that you want."
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@melinosauriorex"   # required for Twitter Cards
